<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="10" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24653" started-at="2020-02-06T14:00:22Z" finished-at="2020-02-06T14:00:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24653" started-at="2020-02-06T14:00:22Z" finished-at="2020-02-06T14:00:46Z">
      <class name="org.failed.TestFailed">
        <test-method status="PASS" signature="startTest()[pri:0, instance:org.failed.TestFailed@548e7350]" name="startTest" is-config="true" duration-ms="22562" started-at="2020-02-06T14:00:22Z" finished-at="2020-02-06T14:00:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="PASS" signature="tc001()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc001" duration-ms="281" started-at="2020-02-06T14:00:44Z" finished-at="2020-02-06T14:00:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc001 -->
        <test-method status="PASS" signature="tc002()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc002" duration-ms="1" started-at="2020-02-06T14:00:45Z" finished-at="2020-02-06T14:00:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc002 -->
        <test-method status="FAIL" signature="tc003()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc003" duration-ms="1" started-at="2020-02-06T14:00:45Z" finished-at="2020-02-06T14:00:45Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at org.failed.TestFailed.tc003(TestFailed.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc003 -->
        <test-method status="FAIL" signature="tc004()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc004" duration-ms="3" started-at="2020-02-06T14:00:46Z" finished-at="2020-02-06T14:00:46Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at org.failed.TestFailed.tc004(TestFailed.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc004 -->
        <test-method status="PASS" signature="tc005()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc005" duration-ms="1" started-at="2020-02-06T14:00:46Z" finished-at="2020-02-06T14:00:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc005 -->
        <test-method status="PASS" signature="tc006()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc006" duration-ms="1" started-at="2020-02-06T14:00:46Z" finished-at="2020-02-06T14:00:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc006 -->
        <test-method status="FAIL" signature="tc007()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc007" duration-ms="2" started-at="2020-02-06T14:00:46Z" finished-at="2020-02-06T14:00:46Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at org.failed.TestFailed.tc007(TestFailed.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc007 -->
        <test-method status="PASS" signature="tc008()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc008" duration-ms="1" started-at="2020-02-06T14:00:46Z" finished-at="2020-02-06T14:00:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc008 -->
        <test-method status="PASS" signature="tc009()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc009" duration-ms="1" started-at="2020-02-06T14:00:46Z" finished-at="2020-02-06T14:00:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc009 -->
        <test-method status="PASS" signature="tc010()[pri:0, instance:org.failed.TestFailed@548e7350]" name="tc010" duration-ms="1" started-at="2020-02-06T14:00:46Z" finished-at="2020-02-06T14:00:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc010 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.failed.TestFailed@548e7350]" name="quit" is-config="true" duration-ms="241" started-at="2020-02-06T14:00:46Z" finished-at="2020-02-06T14:00:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- org.failed.TestFailed -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
